### ISSUE TITLE
Bug? goroutine in importing

### ISSUE THREAD

**Issue by hajimehoshi** [j7b/jsplayground#2]
https://github.com/j7b/jsplayground/blob/master/jsplayground.go#L190

In theory, executing a goroutine is deferred by infinite time, so it looks like there is not guarantee that `g.packages[path] = p` is called before accessing `g.packages[path]`. Is the goroutine there really needed?

**Comment by hajimehoshi** [comment]
The same potential problem is at `go imports()`

https://github.com/j7b/jsplayground/blob/master/jsplayground.go#L174

**Comment by j7b** [comment]
Synchronous import resolution option with https://github.com/j7b/jsplayground/commit/d1b47bd7fbcfbcc7f36cc7d88e7f0bda42bf713a
