### ISSUE TITLE
Can two 'main' packages be in separated directories?

### ISSUE THREAD

**Issue by hajimehoshi** [j7b/jsplayground#9]
Now there are two main packages in the same directory, and I was confused that the binary 'jsplayground' indicated which main package. Can we separate them in separate directories?

BTW, I think `gopherjs install github.com/j7b/jsplayground` doesn't make sense at https://github.com/j7b/citesting/blob/master/.travis.yml and the `jsplayground` binary is already installed by `go get -v github.com/j7b/jsplayground`.

**Comment by j7b** [comment]
They just ended up together because in my first iterations binary and js shared more code. In terms of the travis script, go get jsplayground compiles generate.go to bin, gopherjs install jsplayground builds playground.js in bin

**Comment by hajimehoshi** [comment]
OK but sharing code can be done even if they are in different directories.

> gopherjs install jsplayground builds playground.js in bin

I was wondering if `gopherjs build -m -o jsplayground.js jsplayground.go` is enough or not.

**Comment by j7b** [comment]
Generate now at https://github.com/j7b/jsgen

**Comment by hajimehoshi** [comment]
👍
